language: php
php:      5.4

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - "mkdir -p ~/.composer"
    - cp .composer.config.json ~/.composer/config.json
    - composer install --dev -v --prefer-dist
    - app/console doctrine:database:create -e=test
    - app/console doctrine:schema:create -e=test --no-interaction
    - phantomjs --webdriver=4444 > /dev/null 2>&1 &
    - php -S localhost:8080 -t web > /dev/null 2>&1 &

script:
    - bin/phpspec run -fpretty --verbose
    - bin/behat --no-snippets --verbose