fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        kitten:
            client: default
            types:
                cat:
                    mappings:
                        name: { boost: 5 }
                    persistence:
                        driver: orm
                        model: App\Entity\Cat
                        provider: ~
                        listener: ~
                        finder: ~