# https://github.com/KnpLabs/geekweek12/wiki/Routing

app_home:
    pattern: /
    defaults:
        _controller: 'App:Cat:index'
        _resources:
            "cats": {service: "app.entity.cat_repository", method: "findAll"}

app_search:
    pattern: /search
    defaults:
        _controller: 'App:Search:search'

'App:Cat':
    defaults:
        _resources:
            "cats": {service: "app.entity.cat_repository", method: "findAll"}